### PR TITLE
Modified extension node data added to storage/account leaf

### PR DESCRIPTION
**Pull request by miha-stopar**
Modified extension node is a very rare occurrence and for this reason we do not add the witness to the branch (it would mean increasing the number of branch rows), but to the leaf. The witness data enables to ensure that the extension node was modified correctly - it splits into two extension nodes where the combined nibbles of the two need to be exactly the nibbles of the original extension node.

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Hi @miha-stopar, can we apply the go format before the review?

**Comment by miha-stopar** [comment]
> Hi @miha-stopar, can we apply the go format before the review?

Hey @ChihChengLiang, sorry, I forgot to open it as a draft, it's not yet ready for review. Changed to draft now.

**Comment by ChihChengLiang** [comment]
Hi @miha-stopar,
I attempted to port this branch to zkevm-circuits. You can create a pull request with the following link.

https://github.com/privacy-scaling-explorations/zkevm-circuits/compare/ext-node-additional-rows?expand=1

For some technical detail, I found a way to apply commits from this repo to the the now subfolder in zkevm-circuits.

The trick is to turn commits into patch files then applying them on the subfolder.

In `mpt-witness-generator` repo, we rebased the current branch to main and get ext-node-additional-rows-rebased. We turn the commits to patches with this command. The command outputs patch files.

```
git format-patch ext-node-additional-rows-rebased...main
```

We copy the patch files to zkevm-circuits repo and run the following command to apply patches to mpt-witness-generator sub-directory.

```
git am --directory=mpt-witness-generator *.patch
```

The result is the branch in the above link.

**Comment by miha-stopar** [comment]
Wonderful!! Many thanks @ChihChengLiang !!

**Comment by ChihChengLiang** [comment]
We've ported the PR to https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1598.
Close in favor of the new PR.

**Pull request closed without merging**
